colorWindow              = '#111111'
colorBackground          = '#444444'
colorWindowFocus         = '#222222'
colorBackgroundFocus     = '#666666'
colorBackgroundSelect    = '#DDDDDD'
colorWindowPressed       = '#111111'
colorBackgroundPressed   = '#222222'
colorBorderButton        = '#444444'
colorBorderWidget        = '#777777'
colorCheck               = '#CCCCCC'
colorListBackground      = '#222222'
colorListAlternate       = '#333333'
colorText                = '#CCCCCC'
colorTextFocus           = '#FFFFFF'
colorTextSelection       = '#111111'
colorGraphBackground     = '#222222'
colorLabel               = '#BBBBBB'
colorTitle               = '#DDDDDD'
colorGrid                = '#333333'
colorLine                = []
colorLine.append('yellowgreen') # 'lime'
colorLine.append('dodgerblue')  # 'roaylblue'
colorLine.append('#FFDF33')     # '#FFD119' '#ffdf33' 'sandybrown' 'orange'
colorLine.append('tomato')
colorPositive = 'lime'
colorNegative = '#FF3333'
colorVeryNegative = 'red'
